# Dockerfile for a Python microservice
FROM python:3

# Set the maintainer label
LABEL maintainer="gtuazon@my.bcit.ca"

# Create the application directory
RUN mkdir /app

# Copy the requirements file first to leverage Docker’s cache
COPY requirements.txt /app/requirements.txt

# Set the working directory
WORKDIR /app
RUN pip3 install setuptools
# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the source code into the container
COPY . /app

# Change ownership of the app folder to a non-privileged user
RUN chown -R nobody:nogroup /app

# Switch to the non-privileged user
USER nobody

# Expose the port
EXPOSE 8100

# Set the default command to run the service
CMD ["python", "app.py"]
